# -*- coding: utf-8 -*-
"""Irrigation and fertilizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdNYtwTfx4XL9ikh2dLf19n41bmeoKSu
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
import seaborn as sns

df = pd.read_csv('/content/Pakistan_Major_Crops_High_Favourability_Dataset_With_Moisture.csv')

df

df.columns

# Encode the 'Crop' column
label_encoder = LabelEncoder()
df['crop_encoded'] = label_encoder.fit_transform(df['Crop'])


# -----------------------------
# 🔸 Fertilizer Recommendation
# -----------------------------
fertilizer_features = ['Temperature', 'pH', 'EC', 'Moisture', 'crop_encoded']
fertilizer_targets = ['N', 'P', 'K']

X_fert = df[fertilizer_features]
y_fert = df[fertilizer_targets]

X_train_f, X_test_f, y_train_f, y_test_f = train_test_split(X_fert, y_fert, test_size=0.2, random_state=42)

fert_model = RandomForestRegressor(random_state=42)
fert_model.fit(X_train_f, y_train_f)
fert_preds = fert_model.predict(X_test_f)

print("\n🔹 Fertilizer Prediction (N, P, K):")
print("R2 Score:", r2_score(y_test_f, fert_preds))

# -----------------------------
# 🔸 Irrigation Recommendation
# -----------------------------
irrigation_features = ['Temperature', 'pH', 'EC', 'crop_encoded']
irrigation_target = 'Moisture'

X_irrig = df[irrigation_features]
y_irrig = df[irrigation_target]

X_train_i, X_test_i, y_train_i, y_test_i = train_test_split(X_irrig, y_irrig, test_size=0.2, random_state=42)

irrig_model = RandomForestRegressor(random_state=42)
irrig_model.fit(X_train_i, y_train_i)
irrig_preds = irrig_model.predict(X_test_i)

print("\n🔹 Irrigation (Moisture) Prediction:")
print("R2 Score:", r2_score(y_test_i, irrig_preds))

# -----------------------------
# ✅ Example Prediction
# -----------------------------
example_fert_input = pd.DataFrame([{
    'Temperature': 17.5,
    'pH': 6.4,
    'EC': 1.1,
    'Moisture': 60.0,
    'crop_encoded': label_encoder.transform(['Wheat'])[0]
}])

example_irrig_input = pd.DataFrame([{
    'Temperature': 17.5,
    'pH': 6.4,
    'EC': 1.1,
    'crop_encoded': label_encoder.transform(['Wheat'])[0]
}])

fert_output = fert_model.predict(example_fert_input)
irrig_output = irrig_model.predict(example_irrig_input)

print("\n🔎 Prediction for input (Wheat, 17.5°C, pH 6.4, EC 1.1, Moisture 60%):")
print(f"Recommended NPK: N={fert_output[0][0]:.1f}, P={fert_output[0][1]:.1f}, K={fert_output[0][2]:.1f}")
print(f"Recommended Moisture: {irrig_output[0]:.1f}%")

